apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cicd-demo
  template:
    metadata:
      labels:
        app: my-cicd-demo
    spec:
      containers:
      - name: my-cicd-demo
        image: image: vesahadergjonaj/my-cicd-demo:v1
        ports:
        - containerPort: 80

